"""04_Add_remind_show_field

Revision ID: 380592f49f55
Revises: 90c4ccaf0af2
Create Date: 2024-02-04 17:16:19.676128

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '380592f49f55'
down_revision: Union[str, None] = '90c4ccaf0af2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('azucafe_job', schema=None) as batch_op:
        batch_op.add_column(
            sa.Column('remind_show', sa.Boolean(), nullable=True)
        )

    with op.batch_alter_table('azucafe_payment', schema=None) as batch_op:
        batch_op.alter_column(
            'order_id', existing_type=sa.INTEGER(), nullable=True
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('azucafe_payment', schema=None) as batch_op:
        batch_op.alter_column(
            'order_id', existing_type=sa.INTEGER(), nullable=False
        )

    with op.batch_alter_table('azucafe_job', schema=None) as batch_op:
        batch_op.drop_column('remind_show')

    # ### end Alembic commands ###
