"""01 Init db

Revision ID: f1cacb3a65d8
Revises: 
Create Date: 2023-12-27 12:07:09.548060

"""
from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'f1cacb3a65d8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        'azucafe_cafe',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('phone', sa.String(), nullable=True),
        sa.Column('address', sa.String(), nullable=True),
        sa.Column('map_link', sa.String(), nullable=True),
        sa.Column('picture', sa.String(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_category',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('description', sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_job',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('chat_id', sa.BigInteger(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('data', sa.JSON(), nullable=True),
        sa.Column('scheduled_time', sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_user',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('telegram_id', sa.String(), nullable=True),
        sa.Column('name', sa.String(), nullable=True),
        sa.Column('phone_number', sa.String(), nullable=True),
        sa.Column('admin', sa.Boolean(), nullable=True),
        sa.Column('superuser', sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_order',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('date', sa.DateTime(), nullable=False),
        sa.Column('buyer_id', sa.Integer(), nullable=True),
        sa.Column('guests', sa.Integer(), nullable=True),
        sa.Column('from_date', sa.DateTime(), nullable=True),
        sa.Column('to_date', sa.DateTime(), nullable=True),
        sa.Column('is_cancelled', sa.Boolean(), nullable=True),
        sa.Column('is_paid', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.Column('cafe_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['buyer_id'],
            ['azucafe_user.id'],
        ),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['azucafe_cafe.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_set',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('name', sa.String(), nullable=False),
        sa.Column('category_id', sa.Integer(), nullable=True),
        sa.Column('picture', sa.String(), nullable=True),
        sa.Column('cost', sa.Integer(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['category_id'],
            ['azucafe_category.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_table',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('cafe_id', sa.Integer(), nullable=True),
        sa.Column('table_number', sa.Integer(), nullable=False),
        sa.Column('seats_count', sa.Integer(), nullable=True),
        sa.Column('available', sa.Boolean(), nullable=True),
        sa.Column('description', sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ['cafe_id'],
            ['azucafe_cafe.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_booking',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('table_id', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['azucafe_order.id'],
        ),
        sa.ForeignKeyConstraint(
            ['table_id'],
            ['azucafe_table.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    op.create_table(
        'azucafe_menu',
        sa.Column('id', sa.Integer(), nullable=False),
        sa.Column('order_id', sa.Integer(), nullable=True),
        sa.Column('set_id', sa.Integer(), nullable=True),
        sa.Column('quantity', sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(
            ['order_id'],
            ['azucafe_order.id'],
        ),
        sa.ForeignKeyConstraint(
            ['set_id'],
            ['azucafe_set.id'],
        ),
        sa.PrimaryKeyConstraint('id'),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('azucafe_menu')
    op.drop_table('azucafe_booking')
    op.drop_table('azucafe_table')
    op.drop_table('azucafe_set')
    op.drop_table('azucafe_order')
    op.drop_table('azucafe_user')
    op.drop_table('azucafe_job')
    op.drop_table('azucafe_category')
    op.drop_table('azucafe_cafe')
    # ### end Alembic commands ###
